env:
  matrix:
  - TRAVIS_PYTHON_VERSION="2.7"
  - TRAVIS_PYTHON_VERSION="3.5"
  global:
    secure: ujsscZW+QJkUnKM8YspcAr0u2faqwARY7v7pBaneOIAcLzljV+XDEBfM8ze/SGIdtzJUWy3aoU7dPjdfSdTidLFod1HJKlAuLvpzWpRrYaTtuPuKHzIuXOaJOnysEqSAnLDh5C1gWxQqC7HZfxwtHT3uKOPLuyohrNrmxELXGCg=
os:
- linux
- osx
sudo: false
install:
- echo "Build on $TRAVIS_OS_NAME"
- if [[ "$TRAVIS_TAG" == v* ]]; then export BUILD_STR=""; else export BUILD_STR="dev"; fi
- bash .ci/travis/install_python.sh
- export PATH="$HOME/miniconda/bin:$PATH"
- conda build -q conda-recipe
- conda install -q standard_names --use-local
script:
- nosetests --with-doctest standard_names
after_success:
- bash .ci/travis/deploy_to_anaconda.sh
