package:
  name: standard_names
  version: {{"0.2.2" + environ.get('BUILD_STR', '')}}

source:
  path: ..

requirements:
  build:
    - setuptools
    - python
    - pyyaml
    - six
  run:
    - python
    - pyyaml
    - nose
    - six
