package:
  name: standard_names
  version: "0.2.2"

source:
  path: ..

requirements:
  build:
    - setuptools
    - python
    - pyyaml
    - nose

  run:
    - python
    - pyyaml

build:
  string: {{ environ.get('BUILD_STR', '') }}
