{% set name = "standard_names" %}
{% set version = "0.2.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pyyaml
    - six

test:
  imports:
    - standard_names
  requires:
    - pytest
  commands:
    - snbuild --help
    - sndump --help
    - snscrape --help
    - snsql --help
    - snvalidate --help
    - pytest --pyargs standard_names --doctest-modules -o doctest_optionflags="NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - snbuild = standard_names.cmd.snbuild:run
    - sndump = standard_names.cmd.sndump:run
    - snscrape = standard_names.cmd.snscrape:run
    - snsql = standard_names.cmd.snsql:run
    - snvalidate = standard_names.cmd.snvalidate:run

about:
  home: https://github.com/csdms/standard_names
  license: MIT
  license_file: LICENSE
  summary: Python utilities for working with CSDMS standard names.
  dev_url: https://github.com/csdms/standard_names
